### ISSUE TITLE
function to save slideshow as a xml file 

### ISSUE THREAD

**Issue by RayRaymond** [mvysny/photocloud-frame-slideshow#122]
#function to save slideshow as a xml file.
thank u for the nice product. if there is a save to file function that will be perfect!

**Comment by mvysny** [comment]
I'm not sure I understand - what would be the contents of the XML file please? Could you paste an example XML file which you would expect?

**Comment by RayRaymond** [comment]
Just save the slideshow settings to files.
and the files linked to your app.
so i can start different slideshow just from one click on the different
file.

Best Regards,
>>>>>>>>>>>>>>>>

**Comment by mvysny** [comment]
Unfortunately that's not possible, at least not in a generic way. The reason is that most cloud vendors generate so-called "tokens" as a means to access your cloud-stored files. The tokens are tied to a particular device and are not transferrable to another device (the token may not work elsewhere since it's tied to the device ID).

Some cloud storages are only protected by username/password (e.g. Samba) and those are transferrable, so the XML approach would work for those streams...

**Comment by andyfrei** [comment]
> Unfortunately that's not possible, at least not in a generic way. The reason is that most cloud vendors generate so-called "tokens" as a means to access your cloud-stored files. The tokens are tied to a particular device and are not transferrable to another device (the token may not work elsewhere since it's tied to the device ID).
> 
> Some cloud storages are only protected by username/password (e.g. Samba) and those are transferrable, so the XML approach would work for those streams, but definitely not for all streams.

What would them working ones be? Maybe that could help the community to vote for the feature or not... me for myself, I would be happy if Google Photos and/or Synology NAS storage would work...;-)

**Comment by mvysny** [comment]
No problem :) synology nas - that's either ssh or samba, both should work
with the xml just fine. Google photos is token-based and highly secured,
that one unfortunately won't work for sure.

Best,
Martin

**Comment by mvysny** [comment]
I'm not sure I understand the use-case. Would you like to save a slideshow configuration on one device and load it on another? If you do not need the settings to be portable cross-device, then I do not even need to use XML and I can save in a binary format. I can also save to app settings and simply offer you a picker - a list of settings to load from. Also we're probably not talking about entire settings, just the slideshow list?

**Comment by andyfrei** [comment]
Correct. Basically working towards this scenario:

 Having an old tablet sitting somewhere (maybe tucked to a wall), but I actually don't want to touch at all - or at least as less as possible - once general settings for wakeup/reboot/slideshow autostart etc. are done.
From time to time I would just like to update a gallery, most likely the autostart gallery, adjust some gallery specific settings - done.
For better convenince I'd prefer doing that on the couch on my phone/at android desktop and just send the settings somehow to the tablet.

**Comment by RayRaymond** [comment]
Dear Martin

for me, i dont need cross device.
binary format is fine, i just want switch to different screen saver
showing pictures about my different client when they come to my
office.
in very easy way.
thanks.

Best Regards,
>>>>>>>>>>>>>>>>
Ray Shun

**Comment by RayRaymond** [comment]
maybe a picker +  a cache cleaner
is better for switch screen saver

Best Regards,
>>>>>>>>>>>>>>>>
Ray Shun

**Comment by mvysny** [comment]
@RayRaymond I was exactly thinking about some kind of a "profile" switcher. Could you please open a new feature request though, since it seems to me that your use-case feels a bit different than Andy's use-case?

**Comment by mvysny** [comment]
@RayRaymond I've just implemented #132 and I think that the 'clone' functionality could be helpful also in your case. What you will be able to do is to clone a Stream, name it differently and root it in a different folder. That way, you can have one Stream showing pictures from `/clients/my_first_client`, other Stream showing pictures from `/clients/my_other_client`.

**Comment by andyfrei** [comment]
I think this is great functionality, well done!
Still missing a send to or export/import function of the stream with, but may not be anymore necessary now...

**Comment by mvysny** [comment]
Closing as fixed; if you have any doubts, please reopen and let me know why the 'Clone' functionality doesn't cover your use-case. Thank you :)
