### ISSUE TITLE
'Unauthenticated' Error message pop ups randomly for photo's using OneDrive

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#35]
v1.9.6

Using OneDrive and Screensaver/Daydream functionality

I still get the following error message sometimes. It happens randomly for various pictures. I even wrote the images for which the error happened down and put them all in one folder and let photocloud display only the photo's which resulted in an error. And photocloud displayed those pictures correctly for several hours in a row. So it is not something which is caused by the specific photo's. Perhaps you can adjust the app that whenever such an error happens it just retries to open the photo, or go to the next photo or restarts the app (that's what I'm doing manually now every time).

![image](https://user-images.githubusercontent.com/17165733/29718220-43cba1fc-89b2-11e7-9e35-fc1d116f86a5.png)

**Comment by mvysny** [comment]
That's weird. It seems to be coming from the OneDrive; I do not know why it comes so irrationally. Sure, I can implement a retry mechanism as you suggest. For starters, the algorithm can retry, say, 3 times, with 300ms pause between requests, and let's observe how that helped.

**Comment by mvysny** [comment]
Since I can't reproduce this issue, I had to implement a blind-fix, hopefully the blind fix will work. I'll close this as fixed, please reopen if you will still experience this kind of behavior.

**Comment by mvysny** [comment]
I wonder, may this be perhaps caused by another client (say, the Windows OneDrive client) uploading new photos? Just a guess. Anyways, should be fixed in 1.9.7, please let me know whether it helps. Please wait a bit for 1.9.7 to be released, I'd like to try to add support for raws.

**Comment by JesperJanssen** [comment]
I still get the error message sometimes. Is it an idea to increase the pause to 3 secs instead of 300 ms. And maybe as a last resort do a reboot of the slideshow if the error message stays on the screen for a longer time as the time delay set for the picture change in the slideshow (don't know if that is easy to program)

**Comment by mvysny** [comment]
I can try to increase the pause to 3 seconds. Also it is true that the error message should not block and stop the entire slideshow (unless it's a dealbreaker like can't connect or offline or something like that). Can you please confirm that the error message is shown less frequently (and we're going in the right direction)?

**Comment by JesperJanssen** [comment]
I do believe the error message is shown less frequent

**Comment by mvysny** [comment]
Okay, so it seems that we're on the right track there. I will thus try to increase the pause and increase the retry counts to 5. Let's try out whether that will improve the situation in some way.

**Comment by mvysny** [comment]
Ok, I have increased the retry count to 5; the delay increases from 1s to 2s, 3s, 4s and 5s respectively. Let's see what happens. Fixed in PhotoCloud 1.9.8
