### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by amingle4** [mvysny/photocloud-frame-slideshow#88]
Reference https://github.com/mvysny/photocloud-frame-slideshow/issues/80#issuecomment-380682843

Unsure what to do to provide the requested logs.

**Comment by amingle4** [comment]
I see the FAQ on how to provide the log, so I'll have to try and see if I can figure it out.

**Comment by mvysny** [comment]
Yup - please try to follow http://www.android-photo-frame.eu/faq.html section "Reporting crashes"

**Comment by mvysny** [comment]
Good job, that's exactly what I need.

So the Crash reporting tool crashes, but only on certain Android versions. How typical of Android. *sigh* what a shitty platform.

According to https://stackoverflow.com/questions/32097150/fabric-crashlytics-noclassdeffounderror-only-on-certain-devices it may have something to do with Multidex. I tried to force the multidex initialization a bit sooner, let's try whether it helps or not.

I will also force the Crashlytics to a certain version, the `+` notation is just plain stupid.

**Comment by mvysny** [comment]
Or this is helpful: https://docs.fabric.io/android/changelog.html#february-28-2018
I'll upgrade Crashlytics to 2.9.1, let's see what happens.

**Comment by mvysny** [comment]
Ok, still working on my phone. Closing as fixed in 1.11.5 - please test when 1.11.5 is out.

ps: which phone do you have? Is it Android 4.x by any chance?

**Comment by mvysny** [comment]
Not yet fixed, reproducible on Android 4.x and lower. Caused by https://github.com/mvysny/slf4j-handroid/issues/5

**Comment by amingle4** [comment]
Your conclusion is correct - I did upgrade to 1.11.5, and it is still not working.  And correct that it is an Android 4 tablet (I have a newer tablet I'm going to be moving to eventually, but haven't had time yet).  I don't have a way to get my old tablet to Android 5.  Let me know if there's anything else I can provide.

**Comment by mvysny** [comment]
Fixed in 1.11.6

**Comment by amingle4** [comment]
That's the ticket - thanks for the quick fix. Glad to be back up and running.
